<?php

namespace AddressBookBundle\Repository;

use Doctrine\ORM\EntityRepository;
//use Doctrine\DBAL\Connection#createQueryBuilder


/**
 * RankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankRepository extends EntityRepository
{
    public function findByUserId($user_id){
        $ranks = $this->getEntityManager()->createQuery(
            'SELECT r FROM AddressBookBundle:Rank r WHERE r.userId = :user_id ORDER BY r.name ASC'
        )
        ->setParameter("user_id", $user_id)
        ->getResult();
        return $ranks;
    }
    
    public function findAllRanksByUserId($user_id){
        
        return $this->createQueryBuilder('r')
            ->where ('r.userId = :user_id')
            ->orderBy('r.name', 'ASC')
            ->setParameter('user_id', $user_id);
    }

}
